name: audio_play_or_record
description: "A Flutter package for recording and playing audio messages with interactive waveform visualization, seek support, and chat-style UI."
version: 1.0.5
homepage: https://github.com/Siva-Flutter-Dev/audio_play_or_record
repository: https://github.com/Siva-Flutter-Dev/audio_play_or_record
documentation: https://github.com/Siva-Flutter-Dev/audio_play_or_record#readme
license: MIT
keywords:
  - audio
  - record
  - playback
  - waveform
  - chat
  - flutter
  - messaging
  - voice
  - voice-message
  - recorder
  - microphone
  - audio-player
  - audio-recorder
  - audio-widget
  - sound
  - media
  - realtime
  - animation
  - ui

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  record: ^6.1.2
  just_audio: ^0.10.5
  just_waveform: ^0.0.7
  path_provider: ^2.1.2
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
